CREATE TABLE FUN_STUFF(ID NUMERIC NOT NULL PRIMARY KEY, thing1 VARCHAR, thing2 VARCHAR);

INSERT INTO FUN_STUFF(ID, thing1, thing2) VALUES (1, 'rt1', 'rt3');
INSERT INTO FUN_STUFF(ID, thing1, thing2) VALUES (2, 'rt1111', 'rt3341254');